service: dv-oai-srv

frameworkVersion: "4"

custom:
  wsgi:
    app: app.app
  serverlessSsmFetch:
    OPENAI_API_KEY: /serverless/deployment/credentials/openai-api-key-param

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    REGION: ${self:provider.region}
    OPENAI_API_KEY: ${ssm:/serverless/deployment/credentials/openai-api-key-param}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "s3:PutObject"
            - "s3:GetObject"
          Resource:
            Fn::GetAtt: [ DvProductBucket, Arn ]
        - Effect: Allow
          Action:
            - "ssm:GetParameter"
          Resource: "*"


functions:
  api:
    handler: wsgi_handler.handler
    ssmToEnvironment:
      - OPENAI_API_KEY
    environment:
      DV_PRODUCT_BUCKET:
        Ref: DvProductBucket
    events:
      - http:
          path: /process_email
          method: POST
      - http:
          path: /upload_to_bucket
          method: GET

resources:
  Resources:
    DvProductBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dv-product-bucket

plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-ssm-fetch

