service: dv-oai-srv

frameworkVersion: "4"

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    REGION: ${self:provider.region}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /process_email
          method: POST


plugins:
  - serverless-wsgi
  - serverless-python-requirements

